const mongoose = require('mongoose');
const Listing = require('../models/listing');

// Connect to MongoDB
const mongoUrl = process.env.ATLAS_URL;

main().then(() => {
    console.log("Connected to database");
}).catch((err) => {
    console.log(err);
});

async function main() {
    await mongoose.connect(mongoUrl);

  const rawData = [
    ['Lucknow Luxury Apartment', 'Lucknow', 'city'],
    ['Nainital Scenic Lodge', 'Nainital', 'mountain'],
    ['Bhubaneswar Royal Palace Stay', 'Bhubaneswar', 'heritage'],
    ['Pune Urban Homestay', 'Pune', 'city'],
    ['Daman Coastal Homestay', 'Daman', 'beach'],
    ['Coorg Mountain Cabin', 'Coorg', 'adventure'],
    ['Jaipur Heritage Haveli', 'Jaipur', 'heritage'],
    ['Lansdowne Hilltop Cottage', 'Lansdowne', 'mountain'],
    ['Pench Treehouse Stay', 'Pench', 'forest'],
    ['Patan Historic Guesthouse', 'Patan', 'heritage'],
    ['Bandipur Jungle Lodge', 'Bandipur', 'forest'],
    ['Bangalore Serviced Apartment', 'Bangalore', 'city'],
    ['Mandarmani Beach Resort', 'Mandarmani', 'beach'],
    ['Varkala Beachside Hotel', 'Varkala', 'beach'],
    ['Sikkim Adventure Camp', 'Sikkim', 'adventure'],
    ['Mumbai Business Hotel', 'Mumbai', 'city'],
    ['Gokarna Beach Resort', 'Gokarna', 'beach'],
    ['Rishikesh Adventure Camp', 'Rishikesh', 'adventure'],
    ['Jaipur Boutique Hotel', 'Jaipur', 'heritage'],
    ['Mussoorie Hilltop Cottage', 'Mussoorie', 'mountain'],
    ['Chennai Business Hotel', 'Chennai', 'city'],
    ['Wayanad Treehouse Stay', 'Wayanad', 'forest'],
    ['Leh Heritage Haveli', 'Leh', 'mountain'],
    ['Munnar Mountain Homestay', 'Munnar', 'mountain'],
    ['Puri Beachside Hotel', 'Puri', 'beach'],
    ['Shimla Wooden Chalet', 'Shimla', 'mountain'],
    ['Agra Royal Palace Stay', 'Agra', 'heritage'],
    ['Jim Corbett Jungle Lodge', 'Jim Corbett', 'forest'],
    ['Diu Sea View Villa', 'Diu', 'beach'],
    ['Ahmedabad Serviced Apartment', 'Ahmedabad', 'city'],
    ['Tirthan Valley Adventure Camp', 'Tirthan Valley', 'adventure'],
    ['Nainital Hilltop Cottage', 'Nainital', 'mountain'],
    ['Mandarmani Coastal Homestay', 'Mandarmani', 'beach'],
    ['Hampi Royal Palace Stay', 'Hampi', 'heritage'],
    ['Bhopal Business Hotel', 'Bhopal', 'city'],
    ['Kochi Urban Homestay', 'Kochi', 'city'],
    ['Goa Sea View Villa', 'Goa', 'beach'],
    ['Pune Luxury Apartment', 'Pune', 'city'],
    ['Jodhpur Heritage Haveli', 'Jodhpur', 'heritage'],
    ['Coorg Backpacker Hostel', 'Coorg', 'adventure'],
    ['Alibaug Beach Resort', 'Alibaug', 'beach'],
    ['Ooty Mountain Homestay', 'Ooty', 'mountain'],
    ['Daman Coastal Homestay', 'Daman', 'beach'],
    ['Srinagar Scenic Lodge', 'Srinagar', 'mountain'],
    ['Noida Serviced Apartment', 'Noida', 'city'],
    ['Gwalior Boutique Hotel', 'Gwalior', 'heritage'],
    ['Rameswaram Coastal Homestay', 'Rameswaram', 'beach'],
    ['Mussoorie Scenic Lodge', 'Mussoorie', 'mountain'],
    ['Spiti Valley Adventure Camp', 'Spiti Valley', 'mountain'],
    ['Trivandrum Urban Homestay', 'Trivandrum', 'city'],
    ['Mumbai Serviced Apartment', 'Mumbai', 'city'],
    ['Jaipur Royal Palace Stay', 'Jaipur', 'heritage'],
    ['Goa Beach Resort', 'Goa', 'beach'],
    ['Leh Mountain Cabin', 'Leh', 'mountain'],
    ['Pahalgam Scenic Lodge', 'Pahalgam', 'mountain'],
    ['Ahmedabad Luxury Apartment', 'Ahmedabad', 'city'],
    ['Varanasi Heritage Haveli', 'Varanasi', 'heritage'],
    ['Wayanad Eco Retreat', 'Wayanad', 'forest'],
    ['Nagpur Urban Homestay', 'Nagpur', 'city'],
    ['Tawang Hilltop Cottage', 'Tawang', 'mountain'],
    ['Chikmagalur Jungle Lodge', 'Chikmagalur', 'forest'],
    ['Manali Wooden Chalet', 'Manali', 'mountain'],
    ['Chennai Luxury Apartment', 'Chennai', 'city'],
    ['Alibaug Coastal Homestay', 'Alibaug', 'beach'],
    ['Kanha Safari Camp', 'Kanha', 'forest'],
    ['Udaipur Boutique Hotel', 'Udaipur', 'heritage'],
    ['Patan Heritage Haveli', 'Patan', 'heritage'],
    ['Kolad Adventure Camp', 'Kolad', 'adventure'],
    ['Jaisalmer Royal Palace Stay', 'Jaisalmer', 'heritage'],
    ['Darjeeling Mountain Homestay', 'Darjeeling', 'mountain'],
    ['Rishikesh Backpacker Hostel', 'Rishikesh', 'adventure'],
    ['Buxa Eco Retreat', 'Buxa', 'forest'],
    ['Mandarmani Beach Resort', 'Mandarmani', 'beach'],
    ['Nagpur Business Hotel', 'Nagpur', 'city'],
    ['Mussoorie Wooden Chalet', 'Mussoorie', 'mountain'],
    ['Mumbai Luxury Apartment', 'Mumbai', 'city'],
    ['Sunderbans Jungle Lodge', 'Sunderbans', 'forest'],
    ['Mararikulam Beach Resort', 'Mararikulam', 'beach'],
    ['Gangtok Mountain Homestay', 'Gangtok', 'mountain'],
    ['Chandigarh Business Hotel', 'Chandigarh', 'city'],
    ['Jaipur Boutique Hotel', 'Jaipur', 'heritage'],
    ['Pondicherry Coastal Homestay', 'Pondicherry', 'beach'],
    ['Varanasi Historic Guesthouse', 'Varanasi', 'heritage'],
    ['Kolad Riverfront Tent', 'Kolad', 'adventure'],
    ['Nainital Scenic Lodge', 'Nainital', 'mountain'],
    ['Jodhpur Heritage Haveli', 'Jodhpur', 'heritage'],
    ['Guwahati Urban Homestay', 'Guwahati', 'city'],
    ['Coorg Mountain Cabin', 'Coorg', 'adventure'],
    ['Lucknow Business Hotel', 'Lucknow', 'city'],
    ['Tirthan Valley Adventure Camp', 'Tirthan Valley', 'adventure'],
    ['Rameswaram Beach Resort', 'Rameswaram', 'beach'],
    ['Kodaikanal Hilltop Cottage', 'Kodaikanal', 'mountain'],
    ['Mumbai Urban Homestay', 'Mumbai', 'city'],
    ['Ahmedabad Serviced Apartment', 'Ahmedabad', 'city'],
    ['Puri Beachside Hotel', 'Puri', 'beach'],
    ['Bandipur Safari Camp', 'Bandipur', 'forest'],
    ['Chennai Business Hotel', 'Chennai', 'city'],
    ['Mahabalipuram Boutique Hotel', 'Mahabalipuram', 'beach'],
    ['Lansdowne Wooden Chalet', 'Lansdowne', 'mountain'],
    ['Goa Sea View Villa', 'Goa', 'beach'],
    ['Shimla Scenic Lodge', 'Shimla', 'mountain'],
    ['Agra Royal Palace Stay', 'Agra', 'heritage'],
    ['Dehradun Business Hotel', 'Dehradun', 'city'],
    ['Kanha Jungle Lodge', 'Kanha', 'forest'],
    ['Jaipur Heritage Haveli', 'Jaipur', 'heritage'],
    ['Mandarmani Coastal Homestay', 'Mandarmani', 'beach'],
    ['Leh Mountain Cabin', 'Leh', 'mountain'],
    ['Bhopal Business Hotel', 'Bhopal', 'city'],
    ['Rishikesh Adventure Camp', 'Rishikesh', 'adventure'],
    ['Varkala Beachside Hotel', 'Varkala', 'beach'],
    ['Patan Historic Guesthouse', 'Patan', 'heritage'],
    ['Munnar Mountain Homestay', 'Munnar', 'mountain'],
    ['Pune Luxury Apartment', 'Pune', 'city'],
    ['Wayanad Eco Retreat', 'Wayanad', 'forest'],
    ['Mussoorie Hilltop Cottage', 'Mussoorie', 'mountain'],
    ['Nagpur Serviced Apartment', 'Nagpur', 'city'],
    ['Darjeeling Wooden Chalet', 'Darjeeling', 'mountain'],
    ['Goa Beach Resort', 'Goa', 'beach'],
    ['Mumbai Serviced Apartment', 'Mumbai', 'city'],
    ['Jodhpur Boutique Hotel', 'Jodhpur', 'heritage'],
    ['Sikkim Backpacker Hostel', 'Sikkim', 'adventure'],
    ['Udaipur Heritage Haveli', 'Udaipur', 'heritage'],
    ['Pondicherry Coastal Homestay', 'Pondicherry', 'beach'],
    ['Kanha Safari Camp', 'Kanha', 'forest'],
    ['Chennai Luxury Apartment', 'Chennai', 'city'],
    ['Mandarmani Beach Resort', 'Mandarmani', 'beach'],
    ['Nainital Scenic Lodge', 'Nainital', 'mountain'],
    ['Lucknow Urban Homestay', 'Lucknow', 'city'],
    ['Alibaug Coastal Homestay', 'Alibaug', 'beach'],
    ['Patan Historic Guesthouse', 'Patan', 'heritage'],
    ['Bangalore Serviced Apartment', 'Bangalore', 'city'],
    ['Hampi Royal Palace Stay', 'Hampi', 'heritage'],
    ['Spiti Valley Mountain Cabin', 'Spiti Valley', 'mountain'],
    ['Gwalior Boutique Hotel', 'Gwalior', 'heritage'],
    ['Mussoorie Wooden Chalet', 'Mussoorie', 'mountain'],
    ['Kochi Urban Homestay', 'Kochi', 'city'],
    ['Ooty Mountain Homestay', 'Ooty', 'mountain'],
    ['Goa Sea View Villa', 'Goa', 'beach'],
    ['Mumbai Business Hotel', 'Mumbai', 'city'],
    ['Jaipur Heritage Haveli', 'Jaipur', 'heritage'],
    ['Nagpur Luxury Apartment', 'Nagpur', 'city'],
    ['Darjeeling Hilltop Cottage', 'Darjeeling', 'mountain'],
    ['Puri Beachside Hotel', 'Puri', 'beach'],
    ['Kolad Adventure Camp', 'Kolad', 'adventure'],
    ['Ahmedabad Business Hotel', 'Ahmedabad', 'city'],
    ['Manali Mountain Homestay', 'Manali', 'mountain'],
    ['Leh Mountain Cabin', 'Leh', 'mountain'],
    ['Varanasi Heritage Haveli', 'Varanasi', 'heritage'],
    ['Chennai Serviced Apartment', 'Chennai', 'city'],
    ['Bandipur Jungle Lodge', 'Bandipur', 'forest'],
    ['Mandarmani Beach Resort', 'Mandarmani', 'beach'],
    ['Lucknow Business Hotel', 'Lucknow', 'city'],
    ['Daman Coastal Homestay', 'Daman', 'beach'],
    ['Rishikesh Adventure Camp', 'Rishikesh', 'adventure'],
    ['Mumbai Luxury Apartment', 'Mumbai', 'city'],
    ['Coorg Mountain Cabin', 'Coorg', 'adventure'],
    ['Jaipur Royal Palace Stay', 'Jaipur', 'heritage'],
    ['Pondicherry Coastal Homestay', 'Pondicherry', 'beach'],
    ['Wayanad Treehouse Stay', 'Wayanad', 'forest'],
    ['Pune Urban Homestay', 'Pune', 'city'],
    ['Sikkim Backpacker Hostel', 'Sikkim', 'adventure'],
    ['Bhopal Business Hotel', 'Bhopal', 'city'],
    ['Nainital Scenic Lodge', 'Nainital', 'mountain'],
    ['Jodhpur Boutique Hotel', 'Jodhpur', 'heritage'],
    ['Gangtok Mountain Homestay', 'Gangtok', 'mountain'],
    ['Patan Heritage Haveli', 'Patan', 'heritage'],
    ['Kolad Riverfront Tent', 'Kolad', 'adventure'],
    ['Mandarmani Coastal Homestay', 'Mandarmani', 'beach'],
    ['Alibaug Beach Resort', 'Alibaug', 'beach'],
    ['Udaipur Heritage Haveli', 'Udaipur', 'heritage'],
    ['Mumbai Business Hotel', 'Mumbai', 'city'],
    ['Munnar Mountain Homestay', 'Munnar', 'mountain'],
    ['Varkala Beachside Hotel', 'Varkala', 'beach'],
    ['Leh Mountain Cabin', 'Leh', 'mountain'],
    ['Kanha Safari Camp', 'Kanha', 'forest'],
    ['Jaipur Boutique Hotel', 'Jaipur', 'heritage'],
    ['Nagpur Luxury Apartment', 'Nagpur', 'city'],
    ['Darjeeling Wooden Chalet', 'Darjeeling', 'mountain'],
    ['Pondicherry Coastal Homestay', 'Pondicherry', 'beach'],
    ['Manali Hilltop Cottage', 'Manali', 'mountain'],
    ['Chennai Business Hotel', 'Chennai', 'city'],
    ['Rishikesh Adventure Camp', 'Rishikesh', 'adventure'],
    ['Goa Beach Resort', 'Goa', 'beach'],
    ['Lucknow Urban Homestay', 'Lucknow', 'city'],
    ['Wayanad Eco Retreat', 'Wayanad', 'forest'],
    ['Agra Royal Palace Stay', 'Agra', 'heritage'],
    ['Nainital Hilltop Cottage', 'Nainital', 'mountain'],
    ['Mumbai Serviced Apartment', 'Mumbai', 'city'],
    ['Udaipur Boutique Hotel', 'Udaipur', 'heritage'],
    ['Mandarmani Beach Resort', 'Mandarmani', 'beach'],
    ['Kanha Jungle Lodge', 'Kanha', 'forest'],
    ['Mussoorie Wooden Chalet', 'Mussoorie', 'mountain'],
    ['Kolad Adventure Camp', 'Kolad', 'adventure'],
    ['Patan Historic Guesthouse', 'Patan', 'heritage'],
    ['Pondicherry Coastal Homestay', 'Pondicherry', 'beach'],
    ['Bangalore Serviced Apartment', 'Bangalore', 'city']
  ];

const defaultImage = {
  url: 'https://source.unsplash.com/featured/?hotel,resort,travel',
  filename: 'default',
};

const ownerId = '682f4c9afffa12615e3deae9'; // replace with a valid ObjectId from your users collection

const listings = rawData.map(([title, location, category]) => ({
  title,
  location,
  country:'India',
  category,
  description: `Experience the beauty of ${location} with this wonderful ${category} stay.`,
  price: Math.floor(Math.random() * 5000) + 1000,
  images: {defaultImage},
  owner: ownerId,
}));

try {
  await Listing.deleteMany({});
  await Listing.insertMany(listings);
  console.log('✅ Listings inserted successfully!');
  mongoose.connection.close();
} catch (err) {
  console.error('❌ Error inserting listings:', err);
  mongoose.connection.close();
}};